### ISSUE TITLE
Add Af spec to drawing

### ISSUE THREAD

**Issue by cbonsig** [kenaycock/Generic-IVC-Filter#3]
The target Af should be added to the drawing. Ideally, specify something like Af 25 +/-5 C by bend bree recovery method.

**Comment by kenaycock** [comment]
Hi Craig, 

I updated the drawing files as requested:
https://github.com/kenaycock/Generic-IVC-Filter/tree/master/CAD/Rev1.1

I'm looking at Figure 3.3 in the OpenStent manuscript and it appears that an A<sub>f</sub> of 25 °C corresponds to an Austenite elastic modulus of E<sub>A</sub> ≈ 45,000 MPa:
![openstent_manuscript_fig_3 3](https://cloud.githubusercontent.com/assets/5925722/22793817/fcb5987e-eebe-11e6-93ed-529aad0b1eae.png)



However, I performed our preliminary FEA analyses using E<sub>A</sub> = 61,779 MPa
(same constants as in https://github.com/cbonsig/strain-amplitude-volume-fraction/blob/master/Abaqus_6.12-1_Example.inp). If I'm understanding this correctly, then our prototypes will be ≈3/4 as stiff as the computer model for small strains? That's probably fine, but it would be good to know in advance.

Thanks!
Kenny

**Comment by cbonsig** [comment]
I wouldn't use the Open Stent figure as a general reference for Ea vs Af. That chart was intended to show that there is a relationship that can be modeled, but the specifics will depend on the material history. When we do material testing for this component, we will test at two temperatures, and that will give us the Ea vs Af relationship for this material and process. (Ea and the plateau stresses will shift with the difference between Af and environmental temperature -- so the effect of dropping Af by 10 degrees is equivalent to the effect of raising the environment temperature by 10 degrees while holding Af constant -- that's how we can measure the effect of changing Af without actually making components with a different Af)
