### ISSUE TITLE
Proposed fatigue coupon and fatigue fixture designs

### ISSUE THREAD

**Issue by kenaycock** [kenaycock/Generic-IVC-Filter#4]
Hi Karthik and Craig,

We recently revised the design of the generic IVC filter fatigue coupons and also drafted a design for the fatigue fixture. Summary drawings of the proposed designs can be found here:
https://github.com/kenaycock/Generic-IVC-Filter/tree/master/Fatigue_coupon/Rev1.1b

The proposed fatigue coupon is similar to the one we discussed earlier, but:
1. we extended the hub length to 1cm so that the gripping stresses are located farther from the coupon "arm", and 
2. we removed half of the coupon hub so that the coupon is easier to align and clamp. These "half-tube" coupons should also conserve material, since two fatigue coupons can now be cut from the same length of tubing as would be needed for a single coupon with our earlier design.  

Could you take a look and let us know if you have any feedback? In particular, do you anticipate any problems manufacturing these "half-tube" coupons?

Thanks!
Kenny

**Comment by cbonsig** [comment]
Manufacturing should be straightforward, and the test assembly looks reasonable. I suspect that the cyclic strains may be quite low, so if the intent is to test to failure, that might be a challenge with this setup.

**Comment by cbonsig** [comment]
Another thought. We know from the preliminary analysis (https://github.com/kenaycock/Generic-IVC-Filter/blob/master/Preliminary_FEA/Generic_IVC_filter_project_Preliminary_FEA_Summary.pdf) that 1mm deflection achieves about 0.1% strain amplitude. Higher strain amplitudes can be achieved by deflecting the strut down to the hub diameter, or possibly below the hub diameter... However, with the flat plate test fixture, as the deflection approaches a limit somewhere near the hub diameter, the point of contact will change from the tip of the strut to a point closer to the hub. If such extreme deflections prove to me necessary, it may be helpful to change the design of the top plate to reduce its width and ensure that the point of contact remains at the tip of the strut.

**Comment by kenaycock** [comment]
Hi Craig,

I reviewed our earlier FEA simulations that we performed with the current
coupon design and it looks like deflecting the strut down to the hub
diameter only produces a maximum strain amplitude of approximately 0.5% and
requires a vertical stroke displacement of ≈5mm. Deflecting the tip of the
strut *beyond* the hub diameter another ≈5 mm or so will generate a maximum
strain amplitude of approximately 1% (and require a stroke of ≈10mm). So,
we might be able to make the current design work, but it's probably not
ideal for testing to failure.

Yesterday you mentioned the possibility of producing multiple coupon shapes
or sizes. If it's not too much trouble, what would you think of using the
current coupon design (Rev1.1b) to characterize the lower strain amplitudes
(from 0.1% to 0.5%) and a second coupon with a shorter strut length and a
larger angle between the strut and the axis of the hub to characterize the
larger strain amplitudes (from 0.5% up to, say, 1.5%)?

The problem with using a short coupon for the full range of strain
amplitudes we are interested in (from 0.1% to 1.5%) is that, for the small
strain amplitudes like that corresponding to the Valsalva case for the full
device (0.1%), the required displacements are quite small. For example,
based on some analysis I just ran, for a 6mm strut length, 1.5% strain
amplitude corresponds to a stroke displacement of 1.2mm (reasonable), but
0.1% strain amplitude corresponds to a total stroke displacement of only
≈0.1mm. I imagine consistently producing displacements that small over
multiple coupon specimens may be challenging.

Also, I think you are right that we should reduce the width of the top
plate or reposition it so that the contact point remains approximately the
same throughout the fatigue cycle. If we do pursue multiple coupon designs,
we'll need to adjust the design of the top plate accordingly (perhaps by
adding slots to make the plate mounting position variable).

On Mar 22, 2017 23:08, "Craig Bonsignore" <notifications@github.com> wrote:

Another thought. We know from the preliminary analysis (
https://github.com/kenaycock/Generic-IVC-Filter/blob/master
/Preliminary_FEA/Generic_IVC_filter_project_Preliminary_FEA_Summary.pdf)
that 1mm deflection achieves about 0.1% strain amplitude. Higher strain
amplitudes can be achieved by deflecting the strut down to the hub
diameter, or possibly below the hub diameter... However, with the flat
plate test fixture, as the deflection approaches a limit somewhere near the
hub diameter, the point of contact will change from the tip of the strut to
a point closer to the hub. If such extreme deflections prove to me
necessary, it may be helpful to change the design of the top plate to
reduce its width and ensure that the point of contact remains at the tip of
the strut.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kenaycock/Generic-IVC-Filter/issues/4#issuecomment-288604717>,
or mute the thread

**Comment by kenaycock** [comment]
Hi Craig,

I reviewed our earlier FEA simulations that we performed with the current coupon design and it looks like deflecting the strut down to the hub diameter only produces a maximum strain amplitude of approximately 0.5% and requires a total cyclic vertical displacement of ≈3mm (1.5mm displacement amplitude). Deflecting the tip of the strut *beyond* the hub diameter another ≈3 mm, we can generate a maximum strain amplitude of approximately 1.5%. So, we might be able to make the current design work, but it's probably not ideal for testing to failure.
![fatigeu_coupon_Rev1.1b_max_strain_amp_1pt5perc](https://cloud.githubusercontent.com/assets/5925722/24262639/156c0564-0fd1-11e7-8e0a-97d3bf7ae8c0.gif)
***Animation:** Fatigue loading of the "Rev1.1b" coupon, with a total cyclic displacement of the distal end of the strut of 6mm, corresponding to a strain amplitude of approximately 1.5%* 

Yesterday you mentioned the possibility of producing multiple coupon shapes or sizes. If it's not too much trouble, what would you think of using the current coupon design (Rev1.1b) to characterize the lower strain amplitudes (from 0.1% to 0.5%) and a second coupon with a shorter strut length and a larger angle between the strut and the axis of the hub to characterize the larger strain amplitudes (from 0.5% up to, say, 1.5%)?

The problem with using a short coupon for the full range of strain amplitudes we are interested in (from 0.1% to 1.5%) is that, for the small strain amplitudes like that corresponding to the Valsalva case for the full device (0.1%), the required displacements are quite small. For example, based on some analysis I just ran, for a 6mm strut length, 1.5% strain amplitude corresponds to a stroke displacement of 1.2mm (reasonable), but 0.1% strain amplitude corresponds to a total stroke displacement of only ≈0.1mm. I imagine consistently producing displacements that small over multiple coupon specimens may be challenging.

Also, I think you are right that we should reduce the width of the top plate or reposition it so that the contact point remains approximately the same throughout the fatigue cycle. If we do pursue multiple coupon designs, we'll need to adjust the design of the top plate accordingly (perhaps by adding slots to make the plate mounting position variable).

**Comment by cbonsig** [comment]
I think that a second shorter coupon is a good idea. At 1.5% strain, we should be able to get to a condition with high fracture probability in a reasonable number of cycles.

**Comment by kenaycock** [comment]
@cbonsig  @karthikSenthi
Hi Craig, Karthik:

As communicated via e-mail, we recently finished revising our fatigue coupons. I'm uploading the same slide deck that I sent out earlier here for public.

The updated design files can be found here: 
https://github.com/kenaycock/Generic-IVC-Filter/tree/master/Fatigue_coupon/Rev1.2

[05_15_2017_Fatigue_coupons_update.pdf](https://github.com/kenaycock/Generic-IVC-Filter/files/1002437/05_15_2017_Fatigue_coupons_update.pdf)

Let us know if you have any feedback. We plan on testing 10 specimens per condition (so ~50 "high-strain" and ~30 "low-strain" coupons). 

Thanks!
Kenny
